# Generated by Django 3.1 on 2021-04-29 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('level', models.CharField(choices=[('bg', 'Beginner'), ('inter', 'Intermediate'), ('ad', 'Advanced'), ('ex', 'Expert')], default='bg', max_length=250)),
                ('banner', models.ImageField(upload_to='uploads/courses/images/')),
                ('content', tinymce.models.HTMLField()),
                ('tags', models.ManyToManyField(to='articles.Tags')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('num', models.IntegerField(help_text='use this to arrange the lessons serially for each level', unique=True)),
                ('banner', models.ImageField(upload_to='uploads/articles/images/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='If the lesson is ready. Set the status to publish', max_length=10)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('content', tinymce.models.HTMLField()),
                ('summary', models.TextField(help_text='brief summary of the lesson', max_length=500)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField(default=20, null=True)),
                ('author', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='Articles', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='articles.course')),
                ('tags', models.ManyToManyField(to='articles.Tags')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['num', '-publish'],
            },
        ),
    ]
