# Generated by Django 3.1.7 on 2021-03-31 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('course', models.CharField(max_length=250)),
                ('level', models.IntegerField(help_text='use level to determine the difficulty of the lesson')),
                ('num', models.IntegerField(help_text='use this to arrange the lessons serially for each level')),
                ('banner', models.ImageField(upload_to='uploads/articles/images/<django.db.models.fields.CharField>')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='If the lesson is ready. Set the status to publish', max_length=10)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('content', tinymce.models.HTMLField()),
                ('summary', models.TextField(help_text='brief summary of the lesson', max_length=500)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('first', models.BooleanField(default=False, help_text='if this is the first lesson for this level set this field to true')),
                ('last', models.BooleanField(default=False, help_text='if this is the last lesson for this level set this field to true')),
                ('video', models.FileField(null=True, upload_to='uploads/articles/video/<django.db.models.fields.CharField>')),
                ('tags', models.TextField(help_text="separate tags with commas eg 'crypto, socks, forex' ")),
                ('videourl', models.URLField(null=True)),
                ('duraTion', models.DurationField(default=20, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['level', 'num', '-publish'],
            },
        ),
    ]
