# Generated by Django 3.1.7 on 2021-04-03 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('level', models.CharField(choices=[('bg', 'Beginner'), ('inter', 'Intermediate'), ('ad', 'Advanced'), ('ex', 'Expert')], default='bg', max_length=250)),
                ('content', tinymce.models.HTMLField()),
            ],
            options={
                'ordering': ['level', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['num', '-publish']},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='duraTion',
            new_name='duration',
        ),
        migrations.RemoveField(
            model_name='article',
            name='first',
        ),
        migrations.RemoveField(
            model_name='article',
            name='last',
        ),
        migrations.RemoveField(
            model_name='article',
            name='level',
        ),
        migrations.RemoveField(
            model_name='article',
            name='video',
        ),
        migrations.RemoveField(
            model_name='article',
            name='videourl',
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='Articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='banner',
            field=models.ImageField(upload_to='uploads/articles/images/'),
        ),
        migrations.RemoveField(
            model_name='article',
            name='course',
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.CharField(help_text="separate tags with commas eg 'crypto, socks, forex' ", max_length=250),
        ),
        migrations.AddField(
            model_name='article',
            name='course',
            field=models.ManyToManyField(to='articles.Course'),
        ),
    ]
